### ISSUE TITLE
plotting heatmap function

### ISSUE THREAD

**Issue by hhhcce** [GreenleafLab/ChrAccR#1]
I was wondering whether there is a way to plot the heatmap output in the exploratory analysis with more peak regions (like 2000 most variable regions instead of 1000)?

**Comment by demuellae** [comment]
This is currently fixed. However, you can do this manually by getting the counts using `getCounts` and then filtering the resulting table by variance and your desired threshold and then using your favourite heatmap plotting tool

**Comment by hhhcce** [comment]
Thank for the quick reply, Fabian! 

Is the rowname of the output from getCounts in the same order as the se@rowRanges@ranges [se <- getCountsSE(dsa, "IA_prog_peaks")]?



![image](https://user-images.githubusercontent.com/37914377/72014128-4c1b5c00-322d-11ea-9c44-ebeccd7bdae0.png)

**Comment by demuellae** [comment]
yes, they are
