### ISSUE TITLE
hg38 annotation package

### ISSUE THREAD

**Issue by arugula2388** [GreenleafLab/ChrAccR#14]
"We also provide complementary packages that contain genome-specific annotations. We highly recommend installing these annotation packages in order to speed up certain steps of the analysis:"

# Annotation package

Also what is the download link for other annotations example mouse mm10 and human hg19

**Comment by demuellae** [comment]
Here are the download links:
https://muellerf.s3.amazonaws.com/data/ChrAccR/data/annotation/ChrAccRAnnotationHg38_0.0.1.tar.gz
https://muellerf.s3.amazonaws.com/data/ChrAccR/data/annotation/ChrAccRAnnotationMm10_0.0.1.tar.gz
https://muellerf.s3.amazonaws.com/data/ChrAccR/data/annotation/ChrAccRAnnotationHg19_0.0.1.tar.gz
