### ISSUE TITLE
quantile normalization error in vignette

### ISSUE THREAD

**Issue by arugula2388** [GreenleafLab/ChrAccR#15]
# quantile normalization for all region types
dsa_qnorm <- transformCounts(dsa, method="quantile")
Last executed at 2023-04-27 10:17:47 in 21ms
2023-04-27 10:17:47     7.9  STATUS         STARTED Performing quantile normalization
2023-04-27 10:17:47     7.9  STATUS             Region type: promoters_gc_protein_coding
Error in preprocessCore::normalize.quantiles(ChrAccR::getCounts(.object, : ERROR; return code from pthread_create() is 22

Traceback:

1. transformCounts(dsa, method = "quantile")
2. transformCounts(dsa, method = "quantile")
3. .local(.object, ...)
4. preprocessCore::normalize.quan

**Comment by arugula2388** [comment]
traceback
1. transformCounts(dsa, method = "quantile")
2. transformCounts(dsa, method = "quantile")
3. .local(.object, ...)
4. preprocessCore::normalize.quantiles(ChrAccR::getCounts(.object, 
 .     rt, asMatrix = TRUE))

**Comment by demuellae** [comment]
Looks like a parallelization issue in `preprocessCore`. Could you try to install it manually like in these threads?
https://support.bioconductor.org/p/122925/
https://github.com/Bioconductor/bioconductor_docker/issues/22

**Comment by arugula2388** [comment]
Thanks i tried it but it doesnt quite work
​
Last executed at 2023-05-01 12:52:31 in 21.35s
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://bioinfo-r-package-manager.regeneron.regn.com/cran_prod/2021-10-05


Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.1 (2021-08-10)

Installing package(s) 'preprocessCore'

Installation paths not writeable, unable to update packages
  path: /data/miniconda3/envs/R_4.1.x/lib/R/library
  packages:
    Biobase, BiocGenerics, BiocParallel, biocViews, Biostrings, DelayedArray,
    dittoSeq, fansi, GenomeInfoDb, GenomeInfoDbData, GenomicRanges, graph,
    HSMMSingleCell, IRanges, limma, monocle, powerTCR, RBGL, S4Vectors,
    scRepertoire, SummarizedExperiment, XVector, zlibbioc







# quantile normalization for all region types
dsa_qnorm <- transformCounts(dsa, method="quantile")
Last executed at 2023-05-01 12:52:37 in 22ms
2023-05-01 12:52:37     5.6  STATUS                 STARTED Performing quantile normalization
2023-05-01 12:52:37     5.6  STATUS                     Region type: promoters_gc_protein_coding
Error in preprocessCore::normalize.quantiles(ChrAccR::getCounts(.object, : ERROR; return code from pthread_create() is 22

Traceback:

1. transformCounts(dsa, method = "quantile")
2. transformCounts(dsa, method = "quantile")
3. .local(.object, ...)
4. preprocessCore::normalize.quantiles(ChrAccR::getCounts(.object, 
 .     rt, asMatrix = TRUE))

**Comment by arugula2388** [comment]
Resolved with the above advice; thanks!!
