### ISSUE TITLE
mm10?

### ISSUE THREAD

**Issue by arugula2388** [GreenleafLab/ChrAccR#16]
Can you please share the download link for the other species ex mouse mm10?

"We also provide complementary packages that contain genome-specific annotations. We highly recommend installing these annotation packages in order to speed up certain steps of the analysis:

# hg38 annotation package
[install.packages](https://rdrr.io/r/utils/install.packages.html)("https://muellerf.s3.amazonaws.com/data/ChrAccR/data/annotation/ChrAccRAnnotationHg38_0.0.1.tar.gz")"

**Comment by demuellae** [comment]
Here are the download links:
https://muellerf.s3.amazonaws.com/data/ChrAccR/data/annotation/ChrAccRAnnotationHg38_0.0.1.tar.gz
https://muellerf.s3.amazonaws.com/data/ChrAccR/data/annotation/ChrAccRAnnotationMm10_0.0.1.tar.gz
https://muellerf.s3.amazonaws.com/data/ChrAccR/data/annotation/ChrAccRAnnotationHg19_0.0.1.tar.gz
