### ISSUE TITLE
Error in if (!is.element(startStage, dsStages)) logger.error(c("Invalid dataset start stage:",  :    the condition has length > 1

### ISSUE THREAD

**Issue by Chrisdoan9** [GreenleafLab/ChrAccR#19]
Hello ChrAccR,

I try to run your vignette but got this error:

`run_atac("ChrAccR_analysis", "bamFilenameFull", sampleAnnot, genome="hg38", sampleIdCol="sampleId", regionSets=regionSetList, input = NULL)`
2023-08-02 11:48:59     2.6    INFO     Analysis directory already exists
2023-08-02 11:48:59     2.6  STATUS STARTED ChrAccR analysis
Error in if (!is.element(startStage, dsStages)) logger.error(c("Invalid dataset start stage:",  : 
  the condition has length > 1
  
  Would you please have a suggestion? Thank you so much!

**Comment by demuellae** [comment]
Try deleting the ChrAccR_analysis directory if you want to restart the analysis
