### ISSUE TITLE
Annotation packages install issue?

### ISSUE THREAD

**Issue by BenayounLaboratory** [GreenleafLab/ChrAccR#4]
Hi,

I'm trying to pull the annotation package for mm10 after the program stopped with this message: 
```
2021-10-14 13:49:41     4.7  STATUS STARTED Plotting TSS enrichment
2021-10-14 13:49:42     4.7 WARNING     Could not find annotation package: ChrAccRAnnotationMm10
```
However, the function that is there to download it does not seem to work:
```
getChrAccRAnnotationPackage("mm10")
Error in logger.warning(c("Could not find annotation package:", pkgName)) : 
  could not find function "logger.warning"
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ChrAccRAnnotationMm10’

```

Any idea what may be going on there?
Thanks!

**Comment by demuellae** [comment]
Sorry for the confusion. That is not the function to download the package. Please install manually using


`install.packages("https://muellerf.s3.amazonaws.com/data/ChrAccR/data/annotation/ChrAccRAnnotationMm10_0.0.1.tar.gz")`
