### ISSUE TITLE
Converting to narrowPeak or BigWig Format

### ISSUE THREAD

**Issue by astarr1229** [GreenleafLab/ChrAccR#6]
Hi,

I was wondering if there was a way to quickly convert from the ChrAccR style datasets to a narrowPeak, bigwig, or bed format so that I can use it in other programs and visualize peaks.  Does such a utility function exist?  If not, any ideas on how to convert?

Best, Alex.

**Comment by igunduz** [comment]
Hi, 

I  don't know if you could find an answer to your question however, **ChrAccR** has _exportCountTracks_function where you can export tracks as a bed or igv format to visualize

Kind regards,
Irem
