### ISSUE TITLE
TSS enrichment score

### ISSUE THREAD

**Issue by banwang27** [GreenleafLab/ChrAccR#7]
Hi,
I've been trying to use ChrAccR to evaluate my bulk ATAC-seq dataset.
I notice that there are two types of TSS scores:
getTssEnrichment(dsa, id)$tssEnrichment AND getTssEnrichment(dsa, id)$tssEnrichment.smoothed
What's the difference between these two scores and which one we should mainly look at to follow ENCODE's criteria?

Also, I notice these two functions gives inconsistent results:
'getTssEnrichment(dsa, id)$tssEnrichment.smoothed' AND 'getTssEnrichmentBatch(dsa,sampleIds = getSamples(dsa))$tssEnrichment.smoothed'. Could you explain what's the difference? 
Thanks!

**Comment by demuellae** [comment]
Hi,
`tssEnrichment` refers to the enrichment based on raw counts at each position around the TSS. the `smoothed` version is more commonly used (I believe also by ENCODE) and it does a window based smoothing of these raw counts. Hope that helps
